# Site settings are used to personalize your web site.
# You will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable and will be accessible via {{ site.myvariable }}.
title: w3pro # Your site's title
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Jekyll Seo tag:

logo: # URL to a site-wide logo (e.g., /assets/your-company-logo.png)

author:
  name: # Author details for the jekyll-seo-tag gem
  email: # your-email@example.com

twitter:
  username: John Doe # twitter username without the @ symbol

facebook:
 app_id: 1234
 publisher: 1234
 admins: 1234

social:
  name: John Doe # enter your name and list links to social profiles
  links:
    - https://twitter.com/YourName
    - https://www.facebook.com/Your.Name
    - https://www.linkedin.com/in/YourName
    - https://plus.google.com/+YourName
    - https://github.com/YourName
    - https://keybase.io/YourName

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234

lang: it_IT

# Build settings
markdown: kramdown
theme: w3pro
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
#paginate: nil
#paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/rub
